<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Getting Started with R, RStudio, &amp; Quarto Markdown Files</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GettingStarted_files/libs/clipboard/clipboard.min.js"></script>
<script src="GettingStarted_files/libs/quarto-html/quarto.js"></script>
<script src="GettingStarted_files/libs/quarto-html/popper.min.js"></script>
<script src="GettingStarted_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GettingStarted_files/libs/quarto-html/anchor.min.js"></script>
<link href="GettingStarted_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GettingStarted_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GettingStarted_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GettingStarted_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GettingStarted_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<link href="GettingStarted_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="GettingStarted_files/libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#why-r-markdown-and-reproducible-reports" id="toc-why-r-markdown-and-reproducible-reports" class="nav-link" data-scroll-target="#why-r-markdown-and-reproducible-reports"><span class="header-section-number">1.1</span> Why R Markdown and reproducible reports?</a></li>
  <li><a href="#what-is-markdown-and-why-bother" id="toc-what-is-markdown-and-why-bother" class="nav-link" data-scroll-target="#what-is-markdown-and-why-bother"><span class="header-section-number">1.2</span> What is Markdown, and why bother?</a></li>
  <li><a href="#how-to-use-markdown" id="toc-how-to-use-markdown" class="nav-link" data-scroll-target="#how-to-use-markdown"><span class="header-section-number">1.3</span> How to use Markdown</a></li>
  </ul></li>
  <li><a href="#getting-started-with-r-and-rstudio" id="toc-getting-started-with-r-and-rstudio" class="nav-link" data-scroll-target="#getting-started-with-r-and-rstudio"><span class="header-section-number">2</span> Getting started with R and RStudio</a>
  <ul class="collapse">
  <li><a href="#log-onto-rstudio-server" id="toc-log-onto-rstudio-server" class="nav-link" data-scroll-target="#log-onto-rstudio-server"><span class="header-section-number">2.1</span> Log onto RStudio Server</a></li>
  <li><a href="#install-applications-locally-on-your-computer" id="toc-install-applications-locally-on-your-computer" class="nav-link" data-scroll-target="#install-applications-locally-on-your-computer"><span class="header-section-number">2.2</span> Install applications locally on your computer</a></li>
  <li><a href="#become-familiar-with-r-and-rstudio" id="toc-become-familiar-with-r-and-rstudio" class="nav-link" data-scroll-target="#become-familiar-with-r-and-rstudio"><span class="header-section-number">2.3</span> Become familiar with R and RStudio</a></li>
  </ul></li>
  <li><a href="#getting-started-with-markdown" id="toc-getting-started-with-markdown" class="nav-link" data-scroll-target="#getting-started-with-markdown"><span class="header-section-number">3</span> Getting Started with Markdown</a></li>
  <li><a href="#anatomy-of-a-.qmd-file" id="toc-anatomy-of-a-.qmd-file" class="nav-link" data-scroll-target="#anatomy-of-a-.qmd-file"><span class="header-section-number">4</span> Anatomy of a <code>.qmd</code> file</a>
  <ul class="collapse">
  <li><a href="#yaml-header" id="toc-yaml-header" class="nav-link" data-scroll-target="#yaml-header"><span class="header-section-number">4.1</span> YAML header</a>
  <ul class="collapse">
  <li><a href="#set-global-chunk-options-in-quarto" id="toc-set-global-chunk-options-in-quarto" class="nav-link" data-scroll-target="#set-global-chunk-options-in-quarto"><span class="header-section-number">4.1.1</span> Set Global Chunk Options in Quarto</a></li>
  <li><a href="#example-using-the-yaml-header" id="toc-example-using-the-yaml-header" class="nav-link" data-scroll-target="#example-using-the-yaml-header"><span class="header-section-number">4.1.2</span> Example using the YAML header</a></li>
  </ul></li>
  <li><a href="#text" id="toc-text" class="nav-link" data-scroll-target="#text"><span class="header-section-number">4.2</span> Text</a>
  <ul class="collapse">
  <li><a href="#greek-letters-and-equations-with-latex" id="toc-greek-letters-and-equations-with-latex" class="nav-link" data-scroll-target="#greek-letters-and-equations-with-latex"><span class="header-section-number">4.3.1</span> Greek Letters and Equations With LaTeX</a></li>
  </ul></li>
  <li><a href="#chunks" id="toc-chunks" class="nav-link" data-scroll-target="#chunks"><span class="header-section-number">4.4</span> Chunks</a>
  <ul class="collapse">
  <li><a href="#chunk-options" id="toc-chunk-options" class="nav-link" data-scroll-target="#chunk-options"><span class="header-section-number">4.4.1</span> Chunk options</a></li>
  </ul></li>
  <li><a href="#plots" id="toc-plots" class="nav-link" data-scroll-target="#plots"><span class="header-section-number">4.5</span> Plots</a></li>
  <li><a href="#tables" id="toc-tables" class="nav-link" data-scroll-target="#tables"><span class="header-section-number">4.6</span> Tables</a></li>
  </ul></li>
  <li><a href="#markdown-strategies-to-enhance-reproducibility" id="toc-markdown-strategies-to-enhance-reproducibility" class="nav-link" data-scroll-target="#markdown-strategies-to-enhance-reproducibility"><span class="header-section-number">5</span> Markdown strategies to enhance reproducibility</a>
  <ul class="collapse">
  <li><a href="#use-rstudio-projects" id="toc-use-rstudio-projects" class="nav-link" data-scroll-target="#use-rstudio-projects"><span class="header-section-number">5.1</span> Use RStudio projects</a>
  <ul class="collapse">
  <li><a href="#use-relative-file-paths-not-full-file-paths" id="toc-use-relative-file-paths-not-full-file-paths" class="nav-link" data-scroll-target="#use-relative-file-paths-not-full-file-paths"><span class="header-section-number">5.1.1</span> Use relative file paths, not full file paths</a></li>
  <li><a href="#use-the-working-directory" id="toc-use-the-working-directory" class="nav-link" data-scroll-target="#use-the-working-directory"><span class="header-section-number">5.1.2</span> Use the working directory</a></li>
  <li><a href="#notes-on-working-outside-of-rstudio-projects" id="toc-notes-on-working-outside-of-rstudio-projects" class="nav-link" data-scroll-target="#notes-on-working-outside-of-rstudio-projects"><span class="header-section-number">5.1.3</span> Notes on working outside of RStudio projects</a></li>
  </ul></li>
  <li><a href="#automate-preparation-of-the-working-environment" id="toc-automate-preparation-of-the-working-environment" class="nav-link" data-scroll-target="#automate-preparation-of-the-working-environment"><span class="header-section-number">5.2</span> Automate preparation of the working environment</a>
  <ul class="collapse">
  <li><a href="#install-and-load-packages" id="toc-install-and-load-packages" class="nav-link" data-scroll-target="#install-and-load-packages"><span class="header-section-number">5.2.1</span> Install and load packages</a></li>
  </ul></li>
  <li><a href="#use-inline-code" id="toc-use-inline-code" class="nav-link" data-scroll-target="#use-inline-code"><span class="header-section-number">5.3</span> Use inline code</a></li>
  <li><a href="#report-session-information-code-and-functions-in-the-appendix" id="toc-report-session-information-code-and-functions-in-the-appendix" class="nav-link" data-scroll-target="#report-session-information-code-and-functions-in-the-appendix"><span class="header-section-number">5.4</span> Report session information, code, and functions in the Appendix</a>
  <ul class="collapse">
  <li><a href="#session-information" id="toc-session-information" class="nav-link" data-scroll-target="#session-information"><span class="header-section-number">5.4.1</span> Session Information</a></li>
  <li><a href="#code-embedded-in-the-r-markdown-file" id="toc-code-embedded-in-the-r-markdown-file" class="nav-link" data-scroll-target="#code-embedded-in-the-r-markdown-file"><span class="header-section-number">5.4.2</span> Code embedded in the R Markdown file</a></li>
  <li><a href="#functions-defined-in-the-r-markdown-file" id="toc-functions-defined-in-the-r-markdown-file" class="nav-link" data-scroll-target="#functions-defined-in-the-r-markdown-file"><span class="header-section-number">5.4.3</span> Functions defined in the R Markdown file</a></li>
  </ul></li>
  <li><a href="#document-your-code" id="toc-document-your-code" class="nav-link" data-scroll-target="#document-your-code"><span class="header-section-number">5.5</span> Document your code</a></li>
  <li><a href="#follow-a-consistent-style" id="toc-follow-a-consistent-style" class="nav-link" data-scroll-target="#follow-a-consistent-style"><span class="header-section-number">5.6</span> Follow a consistent style</a></li>
  </ul></li>
  <li><a href="#tips-on-rendering-to-a-pdf" id="toc-tips-on-rendering-to-a-pdf" class="nav-link" data-scroll-target="#tips-on-rendering-to-a-pdf"><span class="header-section-number">6</span> Tips on rendering to a PDF</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul class="collapse">
  <li><a href="#session-information-1" id="toc-session-information-1" class="nav-link" data-scroll-target="#session-information-1">Session information</a></li>
  <li><a href="#embedded-code" id="toc-embedded-code" class="nav-link" data-scroll-target="#embedded-code">Embedded code</a></li>
  <li><a href="#custom-functions" id="toc-custom-functions" class="nav-link" data-scroll-target="#custom-functions">Custom functions</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Getting Started with R, RStudio, &amp; Quarto Markdown Files</h1>
<p class="subtitle lead">ENVH 556</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This document was rendered on September 20, 2024.</p>
<p>Credit: This document has benefited by work done by Emily Voldal, Brian High, Lianne Sheppard, Chris Zuidema, and Magali Blanco.</p>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="why-r-markdown-and-reproducible-reports" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="why-r-markdown-and-reproducible-reports"><span class="header-section-number">1.1</span> Why R Markdown and reproducible reports?</h2>
<p>All good data analysis should be reproducible. Markdown is a popular variant of the syntax often used in Wikis, such as Wikipedia. R Markdown is an extension of Markdown to support the execution and rendering of R code within the document. It integrates easily with R to allow you to produce reproducible reports. We will use these tools and reproducible research practices to support your development in this course.</p>
</section>
<section id="what-is-markdown-and-why-bother" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="what-is-markdown-and-why-bother"><span class="header-section-number">1.2</span> What is Markdown, and why bother?</h2>
<p>Just like an R script is better than typing code in the console, using Markdown is better than using an R script. Markdown documents allow you to save your code, the output that corresponds to your code, and a record of how each calculation and figure was created. Not only will this help you with the homework for this class, it’s good practice for doing reproducible research.</p>
<p>Although a <code>.qmd</code> document looks a lot different from an R script, the basics of Markdown are straightforward compared to the rest of R. After you become familiar with the tricks of Markdown, you may find it easier and faster to use than an R script.</p>
</section>
<section id="how-to-use-markdown" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="how-to-use-markdown"><span class="header-section-number">1.3</span> How to use Markdown</h2>
<p>The output (e.g.&nbsp;<code>.html</code> or <code>.pdf</code>) and source (<code>.qmd</code>) documents are optimally used side-by-side so that you can see both the code and its result.</p>
</section>
</section>
<section id="getting-started-with-r-and-rstudio" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Getting started with R and RStudio</h1>
<section id="log-onto-rstudio-server" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="log-onto-rstudio-server"><span class="header-section-number">2.1</span> Log onto RStudio Server</h2>
<p>In ENVH 556 we will ensure that all applications and labs work on either of 2 UW <a href="https://www.rstudio.com/">RStudio</a> servers running on virtual Linux machines:</p>
<ul>
<li>Plasmid, for DEOHS and EPI students: <a href="https://plasmid.deohs.washington.edu/">plasmid.deohs.washington.edu</a>.</li>
<li>SPH server, for all students: <a href="https://rstudio.sph.washington.edu/">rstudio.sph.washington.edu</a></li>
</ul>
<p>If you are off campus, you will need to install and sign into <a href="https://itconnect.uw.edu/connect/uw-networks/about-husky-onnet/">Husky OnNet VPN</a> using your UW NetID to use these servers. Plasmid is connected to you departmental network storage.</p>
<p>In addition to centralized application installation and management, RStudio servers provide users a higher level of performance and security compared to local installations.</p>
<p>Another (non-UW) RStudio server option is <a href="https://rstudio.cloud/">RStudio Cloud</a>.</p>
</section>
<section id="install-applications-locally-on-your-computer" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="install-applications-locally-on-your-computer"><span class="header-section-number">2.2</span> Install applications locally on your computer</h2>
<p>You are welcome to do your work locally on your laptop, but we will not be able to provide support for local installations. You will need the most recent version of RStudio and R. An easy way to do this is to follow directions on a tutorial program (Swirl) which begins by walking you through the process of downloading R and RStudio. Here is the link to the Swirl tutorial: <a href="https://swirlstats.com/students.html" class="uri">https://swirlstats.com/students.html</a>. The first few Swirl lessons cover the “Basics of R Programming” which may help new R users become familiar with R and RStudio.</p>
<p>If, at any point during this process, R tells you that you need to install other packages, do so.</p>
</section>
<section id="become-familiar-with-r-and-rstudio" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="become-familiar-with-r-and-rstudio"><span class="header-section-number">2.3</span> Become familiar with R and RStudio</h2>
<p>The rest of this document focuses on using Markdown in the course. We assume you are already familiar with R and RStudio. If not, there are many resources available to learn R and RStudio. Here are a few suggestions:</p>
<ul>
<li>The <a href="https://r4ds.had.co.nz/">R for Data Science (R4DS)</a> book by Hadley Wickham and Garrett Grolemund.</li>
<li>An R <a href="https://github.com/deohs/r_onramp/blob/master/README.md">“Onramp”</a> made for beginners by the DEOHS <a href="https://github.com/deohs/coders">Coders Group</a>.
<ul>
<li>Within the <a href="https://github.com/deohs/r_onramp/blob/master/r_resources_and_getting_help.md">Resources and getting help</a> section, there are many courses, tutorials, and books we suggest.</li>
</ul></li>
</ul>
</section>
</section>
<section id="getting-started-with-markdown" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Getting Started with Markdown</h1>
<p>To <strong>open a new Markdown document</strong> (<code>.qmd</code>), select ‘File’, ‘New File’, ‘Quarto Document’. You will see a window asking you for some information about your document; R will use this information to fill in some code in the file, which you can change at any time. For now, leave the default HTML setting and fill in whatever you want for the title and author. Save this file, just like you would save an R script.</p>
<p>The following text is included in new Markdown documents you create:</p>
<blockquote class="blockquote">
<p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see https://quarto.org…</p>
</blockquote>
<p>To turn this code into a nicely formatted document, select the <strong>‘Render’</strong> button or run <code>quarto render filename.qmd</code> in the terminal. This will generate the output and save it in the same location as the <code>.qmd</code> file.</p>
<p>You can **run code* line-by-line from the <code>.qmd</code> document as you build it. It can be helpful to render often.</p>
<p>You can use the drop-down menu of the ‘Run’ button in the toolbar for additional options, such as running the next chunk, running all chunks above, or running all chunks. The arrows to the left of the ‘Run’ button can help you navigate through your document, especially when working with larger files.</p>
<p>RStudio’s text editor includes a basic <strong>spell-checker</strong>, which works well for regular text but does not check code or special symbols. To use it, click the button with ‘ABC’ and a green check mark, located to the right of the save button in the toolbar for the text editor panel.</p>
<p>If you’re looking for a more sophisticated option that also checks grammar, you can render the document to a Word file and use Word’s spell-checker. However, avoid pasting code back into the text editor from Word, as MS Word may modify characters (such as quotes), which can break your code.</p>
<p>Here are several good Quarto resources to help you get started:</p>
<ul>
<li><a href="https://quarto.org/">Quarto Website</a></li>
<li><a href="https://quarto.org/docs/authoring/markdown-basics.html">Markdown Basics</a></li>
<li><a href="https://quarto.org/docs/get-started/hello/rstudio.html">Quarto Tutorial</a>
<ul>
<li>Includes Video</li>
</ul></li>
<li><a href="https://quarto.org/docs/guide/">Quarto Guide</a></li>
</ul>
</section>
<section id="anatomy-of-a-.qmd-file" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Anatomy of a <code>.qmd</code> file</h1>
<section id="yaml-header" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="yaml-header"><span class="header-section-number">4.1</span> YAML header</h2>
<p>The header is enclosed by dashes and is always at the top of the file. By default, it will include a title, author, date, and what type of file it will render to. You can change the text of the title, author, and date here any time. These will show up at the top of your knitted document. You can also change the file type at any time. For example, replacing <code>html_document</code> with <code>word_document</code>, will render a Word file. However, be aware that some commands are specific to certain document types, or just show up differently. Generally <code>html_document</code> seems to be the most flexible and least fussy type of output.</p>
<section id="set-global-chunk-options-in-quarto" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="set-global-chunk-options-in-quarto"><span class="header-section-number">4.1.1</span> Set Global Chunk Options in Quarto</h3>
<p>Global chunk options can be set using the YAML header or within individual chunks. These options control how code is rendered throughout the document.</p>
</section>
<section id="example-using-the-yaml-header" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="example-using-the-yaml-header"><span class="header-section-number">4.1.2</span> Example using the YAML header</h3>
<p>You can specify global chunk options in the YAML header of your <code>.qmd</code> file. For example:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span><span class="kw">:</span><span class="at"> </span><span class="st">"Your Document Title"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">format</span><span class="kw">:</span><span class="at"> </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">html</span><span class="kw">:</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="at">    </span><span class="fu">code-fold</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span><span class="co">     # Enables code folding for better readability</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">execute</span><span class="kw">:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">echo</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span><span class="co">           # Hides code output globally</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">warning</span><span class="kw">:</span><span class="at"> </span><span class="ch">false</span><span class="co">        # Suppresses warnings globally</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="at">  </span><span class="fu">cache</span><span class="kw">:</span><span class="at"> </span><span class="ch">true</span><span class="co">           # Enables caching globally</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="pp">---</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You can mix global options in the YAML header and override them for specific chunks when needed.</p>
</section>
</section>
<section id="text" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="text"><span class="header-section-number">4.2</span> Text</h2>
<p>To put plain text into an Markdown document, you don’t need anything special. Text that is black in the <code>.qmd</code> document is plain text in the rendered document.</p>
<p>Blue text in the <code>.qmd</code> indicates that it has been formatted in some way by using special characters (for example, the knitted text may be bold).</p>
<p>There are some things that you might be used to in other text processors (like Word) which aren’t as straightforward in Markdown. When formatting assignments for this class, you should not spend much time making your text ‘pretty’, but your answers should be well-organized. This section will cover some (easy) things to do in Markdown to organize and manipulate text.</p>
<p>You can make font <strong>bold</strong>, or <em>italicized</em>.</p>
<p>You can make numbered lists (see the Table of Contents), or bulleted lists:</p>
<ul>
<li>Item 1</li>
<li>Item 2</li>
</ul>
<p>You can organize your content using <strong>headings</strong>, which are indicated by <code>#</code> (see my section headings). The more pound symbols, the smaller the heading. We show these examples without knitting them:</p>
<pre><code># Title (level 1)
## Subtitle (level 2)  
### Sub-subtitle (level 3)  
#### Sub-sub-subtitle (level 4)</code></pre>
<p>In Quarto, you can use the following for <strong>dividers</strong> and page breaks:</p>
<ul>
<li><p>To insert a horizontal line (divider) in your document, use three or more asterisks (<code>***</code>) or dashes (<code>---</code>):</p>
<h2 id="example" data-number="4.3" class="anchored"><span class="header-section-number">4.3</span> <strong>Example</strong>:</h2></li>
</ul>
<hr>
<ul>
<li>To create a page break (only for certain formats like PDF), use <code>\newpage</code>. Note that this will not work for HTML output.</li>
</ul>
<p>In Quarto, comments enclosed in <!-- --> are hidden in all output formats, allowing you to leave notes or reminders in your source file without them showing up in the final document. For example:</p>
<p><code>&lt;!-- This is a text comment and won't appear in the output --&gt;</code></p>
<!-- This is a text comment and won't appear in the output -->
<section id="greek-letters-and-equations-with-latex" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="greek-letters-and-equations-with-latex"><span class="header-section-number">4.3.1</span> Greek Letters and Equations With LaTeX</h3>
<p>If you want to make your text clearer by using nicely formatted equations, you can use the math language LaTeX to write Greek letters and equations. Below are some examples that you can copy and paste, or just Google it.</p>
<p>This is <em>not</em> an expectation for ENVH 556, it’s just something extra for those of you who are interested. Here is a <a href="https://tilburgsciencehub.com/topics/research-skills/templates-dynamic-content/templates/amsmath-latex-cheatsheet/">Cheatsheet for LaTeX Math Commands</a></p>
<p><span class="math inline">\(\alpha\)</span></p>
<p><span class="math inline">\(\alpha_0\)</span></p>
<p><span class="math inline">\(\alpha_1\)</span></p>
<p><span class="math inline">\(\beta\)</span></p>
<p><span class="math inline">\(\pi\)</span></p>
<p><span class="math inline">\(x_{Exposure}\)</span></p>
<p><span class="math inline">\(e^{\beta}\)</span></p>
<p>So we can write out models:</p>
<p><span class="math inline">\(\log(x_{Disease})=\alpha_0+\beta x_{Exposure}\)</span></p>
<p>or</p>
<p>log(<span class="math inline">\(x_{Disease}\)</span>) = <span class="math inline">\(\alpha_0\)</span> + <span class="math inline">\(\beta\)</span> <span class="math inline">\(x_{Exposure}\)</span></p>
</section>
</section>
<section id="chunks" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="chunks"><span class="header-section-number">4.4</span> Chunks</h2>
<p>Interspersed in the text are lines of code; these may have a shaded background in your file; these are called ‘chunks’. Chunks start with <code>```{r}</code> and end with <code>```</code>, each at the beginning of the line. You can think of each chunk as a miniature R script. If we removed all the text from a <code>.qmd</code>, the chunks would make up the complete R script for that analysis. (The code appendix does this for you automatically; see below.)</p>
<p>Within a Markdown document, your code all needs to be in order (you can’t print a plot after your first paragraph if you don’t load the data set until paragraph three). You also can’t use <em>anything</em> outside the Markdown document; you need to load packages, load data, etc. all within this Markdown document. This will become an issue when you try to render the document, even if it worked while running code straight from the <code>.qmd</code>.</p>
<p>Below is the basic format of a chunk. You can make new chunks by pressing ‘Ctrl’ ‘Alt’ ‘i’ in Windows, or ‘Cmd’ ‘Option’ ‘i’ in Macs.</p>
<p>It is good practice to name every chunk with a word following <code>r</code>, e.g.&nbsp;<code>{r chunk_name_goes_here, and chunk options go after the comma, options separated by commas}</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk-----------</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Code goes here; output appears below</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># By setting the seed, we follow the reproducible research practice that my</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># random numbers are the same each time.</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate random numbers from a Normal distribution and save as a vector.</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">2</span>, <span class="at">n=</span><span class="dv">20</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2168</code></pre>
</div>
</div>
<p>The code and output above would not be acceptable in a homework write-up. You can use chunk options to change how code and output appear in the knitted document (but chunk options don’t affect anything when you are running code chunk by chunk inside the <code>.qmd</code> document). Below, I’ll give some examples of chunk options; check out the knitted document to see what each of them do. Chunk options can be combined by separating them with commas.</p>
<section id="chunk-options" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="chunk-options"><span class="header-section-number">4.4.1</span> Chunk options</h3>
<p>We can control what the code and output of each chunk look like by changing ‘chunk options’.</p>
<p><em>eval=FALSE</em></p>
<p>The following code won’t be run.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----code chunk that will not run----</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This code won't be run!</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(I can type whatever I want because this is not run.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>echo=FALSE</em></p>
<p>The following code won’t be shown, but it will run and the output will be displayed.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2168</code></pre>
</div>
</div>
<p><em>results=“hide”</em></p>
<p>The following output won’t be shown, but the code will still run in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk that will not show output------</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This output won't be shown, but it will still run in R.</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mean_of_a <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>mean_of_a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Hiding Absolutely Everything: include=FALSE</em></p>
<p>To hide absolutely everything, you could use these chunk options:</p>
<p><code>include=FALSE</code></p>
<p>Or, equivalently:</p>
<p><code>echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'</code></p>
<p>For more information about <code>include=FALSE</code>, see: https://yihui.name/en/2017/11/knitr-include-false/</p>
<p>It is possible to hide errors and warnings in your knitted document. <strong>Do not</strong> leave the <code>message=FALSE</code> and <code>warning=FALSE</code> options turned on while you are creating your document because they will hide important messages from R. Just add these when you are done coding; for example, using <code>library()</code> or <code>p_load()</code> often creates some messages which you may wish to hide in your final document. In general, we <em>want</em> to see the messages and warnings from R as we are coding.</p>
<p>The following chunk won’t be shown and it creates output that won’t be shown. However, the code will still run in R.</p>
<p><em>Accept errors: error=TRUE</em></p>
<p>When <code>error=TRUE</code> is set, the document will continue rendering even if the code in the chunk throws an error. Instead of halting the process, Quarto or R Markdown will display the error message in the output document where the error occurred.</p>
<p>This chunk option is a temporary band-aid to help you record and understand the error; <strong>do not</strong> make all your chunks <code>error=TRUE</code> as a way of bypassing code issues.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk accept errors-----</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Sometimes in a work-in-progress, you may want a knitted copy of everything -</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># even things that go wrong. This wouldn't be a chunk option to use in a</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># polished homework assignment. This is an error because I haven't loaded the</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># titanic data in this document yet (regardless of whether it's loaded in my</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># RStudio right now)</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(titanic) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'titanic' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2168</code></pre>
</div>
</div>
</section>
</section>
<section id="plots" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="plots"><span class="header-section-number">4.5</span> Plots</h2>
<p>To print a plot, you don’t need any special chunk options.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example plot-----</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GettingStarted_files/figure-html/example_plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>However, to hide a plot you need to use <code>include=FALSE</code>, which hides all code and output (using <code>results="hide"</code> won’t work on plots).</p>
<p><em>include=FALSE to hide a plot and its code</em></p>
<p>The following chunk is hidden, as is its output.</p>
</section>
<section id="tables" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="tables"><span class="header-section-number">4.6</span> Tables</h2>
<p>Markdown has the ability to create nice tables (nice enough to use for homework). There are several different packages for creating tables; these include <code>kable</code>, <code>stargazer</code>, and <code>xtable</code>. <code>kable</code> is the simplest to use and we show examples in Lab 1. If you wish to develop more sophisticated tables, explore these other packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example table with data generation----</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate some toy data as vectors</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">n =</span> <span class="dv">20</span>, <span class="at">prob =</span> .<span class="dv">5</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>height <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">mean =</span> (<span class="dv">50</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> sex), <span class="at">sd =</span> <span class="dv">10</span>, <span class="at">n =</span> <span class="dv">20</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>hair_color <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"brown"</span>, <span class="st">"black"</span>, <span class="st">"blond"</span>), <span class="at">length =</span> <span class="dv">20</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># combine within a "tibble" dataframe, oriented by columns</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>toy.data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(sex, height, hair_color)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table with the average and standard deviation of height for each </span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># hair color category using `dplyr` functions and the pipe operator, `%&gt;%`, which </span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># feeds the output of one function into the input of the next function. </span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># The `` notation acommodates non-standard variable names.</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>table_df <span class="ot">&lt;-</span> toy.data <span class="sc">%&gt;%</span> </span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hair_color) <span class="sc">%&gt;%</span> </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Average height</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(height), </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">SD of height</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sd</span>(height), </span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">Hair color</span><span class="st">`</span> <span class="ot">=</span> hair_color)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co">#example kable table with caption</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(table_df, <span class="at">caption=</span><span class="st">"Height by hair color"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Height by hair color</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Hair color</th>
<th style="text-align: right;">Average height</th>
<th style="text-align: right;">SD of height</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">black</td>
<td style="text-align: right;">54.97</td>
<td style="text-align: right;">11.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">blond</td>
<td style="text-align: right;">57.08</td>
<td style="text-align: right;">10.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">brown</td>
<td style="text-align: right;">59.95</td>
<td style="text-align: right;">10.78</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="markdown-strategies-to-enhance-reproducibility" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Markdown strategies to enhance reproducibility</h1>
<p>Reproducible reports with embedded data analyses have many benefits, including:</p>
<ul>
<li><p>Eliminates typos and transcription errors by pulling results directly from R</p></li>
<li><p>Automatically updates your results if you change other code (e.g., if I decided to remove one observation from my data set, I wouldn’t have to re-type all my numbers)</p></li>
<li><p>Creates a record of exactly how you calculated every number (so another scientist could easily reproduce your entire analysis, and you will never forget how you calculated something)</p></li>
</ul>
<p>In the remainder of this section, we suggest strategies that support reproducibility.</p>
<section id="use-rstudio-projects" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="use-rstudio-projects"><span class="header-section-number">5.1</span> Use RStudio projects</h2>
<p>An important principle is to keep your scripts, data files, and all other inputs and outputs within a <a href="https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects">project</a> folder. Using an RStudio “project” makes directory organization easy, decreasing reliance on <code>setwd()</code> commands in your scripts. You would not refer to files outside of this project folder, but instead would use subfolders (e.g., “data”, “images”, etc.) to organize your work within your project.</p>
<p>Using project folders also works nicely with version control (Git) as the project folder becomes your version control “repository” for that project.</p>
<p>Let’s make a new RStudio project named “new_project”. In the GUI click:</p>
<p>File –&gt; New Project…</p>
<p>In the dialogue box that appears click:</p>
<p>New Directory –&gt; New Project</p>
<p>We can make “new_project” a subdirectory of: “~/Home” and click “Create Project”</p>
<p>From here if your create a new <code>.qmd</code> file it will automatically be placed within the project’s working directory. We will also set up a new project in the first lab.</p>
<p>The following best practices, used within RStudio projects, promote the reproducibility of your work even more.</p>
<section id="use-relative-file-paths-not-full-file-paths" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="use-relative-file-paths-not-full-file-paths"><span class="header-section-number">5.1.1</span> Use relative file paths, not full file paths</h3>
<p>Best practice is to not include full paths (“C://Project_1/data/raw”) to your files, but uses relative paths (“data/raw”) instead, so they will be more portable – able to run on someone else’s system. Even better, use <strong><code>file.path()</code></strong> to construct these paths to make them platform independent, so a person can use, e.g., Windows, macOS, or Linux to reproduce your results. Windows users take note: paths like “C:\data\raw” or even “data\raw” will not work on a Mac. Use “data/raw”, or better yet, <code>file.path("data", "raw")</code> to solve this problem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----file paths---------</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Only works on Windows, as other modern operating systems (macOS, Linux) do </span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># not support "drive letters", such as "P:"</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'P:</span><span class="sc">\\</span><span class="st">ENVH556'</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'P:/ENVH556'</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Will not work on Windows, exposes your username, and won't work for other </span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># users</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'/Users/joanna/ENVH556'</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># If you are curious about what the "~" expands to, you can use path.expand()</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>full_path_to_home <span class="ot">&lt;-</span> <span class="fu">path.expand</span>(<span class="st">'~'</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>full_path_to_data <span class="ot">&lt;-</span> <span class="fu">path.expand</span>(<span class="st">'~/ENVH556'</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Will work on Windows, macOS, and Linux, etc., if the file is in the user's</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co"># "home directory"</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>relative_path <span class="ot">&lt;-</span> <span class="st">'~/ENVH556'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="use-the-working-directory" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="use-the-working-directory"><span class="header-section-number">5.1.2</span> Use the working directory</h3>
<p>The “working directory” is a directory associated with your default position or location within a file system. For example, if you tell R to look for a file, it assumes you mean within the working directory. It is convenient to make your working directory the highest level directory associated with the files and data for an analysis. Meaning, for example, your <code>.qmd</code> file and the directory containing your data are within your working directory. With RStudio projects, this all becomes easier, because the project automatically “sets” the working directory. You can check the working directory at any time with the <code>getwd()</code> function.</p>
<p>You can even assign the working directory to a variable, to use with relative paths. For example, if you wanted to load an <code>.rds</code> data file within a hypothetical “Datasets” folder contained within your working directory you could do something like this with the helpful <code>file.path()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----relative path example-----</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># assign working directory variable</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>work_dir <span class="ot">&lt;-</span> <span class="fu">getwd</span>()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># build relative path to data file</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>relative_data_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(work_dir, <span class="st">"Datasets"</span>, <span class="st">"data.rds"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># load data, assign to "df" variable</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(relative_data_path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="notes-on-working-outside-of-rstudio-projects" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="notes-on-working-outside-of-rstudio-projects"><span class="header-section-number">5.1.3</span> Notes on working outside of RStudio projects</h3>
<p>When working outside of an RStudio project, you’ll have to specify your working directory. Just like the automatic organization that comes with using a project, you can make your default working directory the location of your <code>.qmd</code> file. If you want to change that default, you can use <code>setwd()</code>. For example, let’s say my RDS file isn’t in the same folder as my <code>.qmd</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----setwd example---------</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a full file path, but it would be better to use a relative one</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"P:/ENVH556"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a relative file path, where ".." means "one folder up"</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"../ENVH556"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a relative file path with file.path(), the recommended method</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># because this method supports muliple computing platforms (Windows, Mac, etc.)</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">file.path</span>(<span class="st">".."</span>, <span class="st">"ENVH556"</span>))</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we are ready to read the file</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>DEMS <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"DEMSCombinedPersonal.rds"</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># You can see that my working directory changed with getwd()</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using working directories would be especially helpful if you needed to load lots of different data files and you didn’t want to type out all the file paths. If you always put your <code>.qmd</code> and data files in the same location, you should be able to use the default working directory without typing file paths.</p>
<p>One mild word of warning: there are some issues with working directories in R Markdown. If you are having trouble, you may want to make sure that <code>setwd()</code> is in the same chunk as your <code>readRDS()</code> command. There is also a more <a href="http://pbahr.github.io/tips/2016/04/16/fix_rmarkdown_working_directory_issue">elegant solution</a> to this.</p>
</section>
</section>
<section id="automate-preparation-of-the-working-environment" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="automate-preparation-of-the-working-environment"><span class="header-section-number">5.2</span> Automate preparation of the working environment</h2>
<p>When you write code in R Markdown it needs to be completely self-contained - that is, it can’t rely on anything you loaded, imported, or run outside of the R Markdown document, e.g., in your RStudio session. An excellent principle is to automate the preparation of the working environment in your R Markdown document. This includes setting options and installing software packages.</p>
<section id="install-and-load-packages" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="install-and-load-packages"><span class="header-section-number">5.2.1</span> Install and load packages</h3>
<p>A key principle is to only load the packages you will need for your project. To facilitate this, use the <strong><code>pacman</code> package</strong> in R instead of <code>install.packages()</code> and <code>library()</code>. This will allow your script to automatically install any packages it needs to without forcing the installation of a package which has already been installed. Here is an example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----setup pacman-----------</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Not evaluated here since done at the beginning of the file</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load pacman into memory, installing as needed</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>my_repo <span class="ot">&lt;-</span> <span class="st">'http://cran.r-project.org'</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>, <span class="at">repos =</span> my_repo)}</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the other packages, installing as needed</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(knitr, tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first part installs <code>pacman</code> if it is missing, then the second part installs and loads the other packages as needed. If you do this at the top of your script for any packages needed later in your script, it makes it really easy for people to see what packages your script depends on. This approach will make it much more likely someone, particularly a new R user, will be able to run your script and reproduce your results. Many new R users get completely stuck if they run code that bombs simply because a package has not been installed. And just putting in <code>install.packages()</code> calls “just in case” will needlessly slow down your script (each and every time it is run) if the packages have already been installed.</p>
</section>
</section>
<section id="use-inline-code" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="use-inline-code"><span class="header-section-number">5.3</span> Use inline code</h2>
<p>One way to ensure reproducibility is to use in-line code. This incorporates R results directly within text. To include code output in a sentence, we use the format of one backtick followed by “r”, a space, and then some R code, and ending with a second backtick. For example, we can write: “The mean of the data is <strong>0.2168</strong>.” We’ve seen above that output from chunks is usually not ‘pretty’ enough for refined reports, so ideally you pay attention to scientific reporting standards, for instance by rounding it to an appropriate number of significant figures: The mean is 0.22. This is much better than directly typing into your text “The mean is 0.217” because it follows several reproducibility principles:</p>
<ul>
<li>Eliminates typos</li>
<li>Automatically updates if you change other code (i.e.&nbsp;if I decided to remove one person from my data set, I wouldn’t have to re-type all my numbers)</li>
<li>Creates a record of exactly how you calculated every number (so another scientist could easily reproduce your entire analysis, and you will never forget how you calculated something)</li>
</ul>
<p>In general, only use the in-line code format for printing out one or two numbers. If you need a table or plot, that needs to come from a chunk.</p>
</section>
<section id="report-session-information-code-and-functions-in-the-appendix" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="report-session-information-code-and-functions-in-the-appendix"><span class="header-section-number">5.4</span> Report session information, code, and functions in the Appendix</h2>
<p>When you turn in assignments, in addition to your well-written answers (which should not have any code or raw output), you will need to include the session information, embedded code, and functions defined in the .qmd in a code appendix.</p>
<p>Both the the <code>LabReportGuidelines.qmd</code> template for ENVH 556 and the appendix at the end of this document provide you with example code to accomplish this.</p>
<section id="session-information" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="session-information"><span class="header-section-number">5.4.1</span> Session Information</h3>
<p>At a minimum, your <code>.qmd</code> should record version numbers of R and your packages with <code>sessionInfo()</code> at the end of your script.</p>
<pre><code>sessionInfo()</code></pre>
</section>
<section id="code-embedded-in-the-r-markdown-file" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="code-embedded-in-the-r-markdown-file"><span class="header-section-number">5.4.2</span> Code embedded in the R Markdown file</h3>
<p>For ENVH 556, we also want to see all of your code consolidated at the end of your R Markdown output. The following code for a chunk header will compile all your code into an appendix code listing. (This next version is for display in the rendered document and not for execution. A working version that is included in the appendix of this document. Note that the chunk header containing these options should be a single line of code with no line-wrap.)</p>
<pre><code>ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE, include=TRUE</code></pre>
</section>
<section id="functions-defined-in-the-r-markdown-file" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="functions-defined-in-the-r-markdown-file"><span class="header-section-number">5.4.3</span> Functions defined in the R Markdown file</h3>
<p>You should also include a list of functions you created for your analysis (i.e.&nbsp;functions used in your analysis that were not part of loaded packages).</p>
<pre><code># Show the names of all functions defined in the .qmd
# (e.g. loaded in the environment)
lsf.str()

# Show the definitions of all functions loaded into the current environment  
lapply(c(lsf.str()), getAnywhere)</code></pre>
<p>Note that there is very little code embedded in these guidelines and no functions, so the second two chunks produce little or no output. Generally your files will have much longer code appendices.</p>
</section>
</section>
<section id="document-your-code" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="document-your-code"><span class="header-section-number">5.5</span> Document your code</h2>
<p>We encourage you to adopt these best practices when commenting your code to improve readability:</p>
<ul>
<li>Comment to keep a running commentary on what your code does.</li>
<li>The level of detail should be enough to clarify but not to enough to annoy.</li>
<li>Insert comments immediately before the line(s) of code to which they apply.</li>
<li>Add spaces and blank lines as needed to separate code and comments.</li>
<li>Avoid “side-commenting”, putting comments at the end of a line of code.</li>
<li>Comments should state what the code does, in the form of an <a href="https://www.wordnik.com/words/imperative">imperative</a>.</li>
</ul>
<p>Here is an example of these put into practice:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----comment example-----------</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector of temperatures in degrees Celcius</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>temps <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">22</span>, <span class="dv">20</span>, <span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">22</span>, <span class="dv">19</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean temperature and standard deviation</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(temps)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(temps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="follow-a-consistent-style" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="follow-a-consistent-style"><span class="header-section-number">5.6</span> Follow a consistent style</h2>
<p>Choose a code style and be consistent within your <code>.qmd</code>. Following established styles will make your code more readable and easier to follow - for both you and others. Here are two popular examples:</p>
<ul>
<li>The <a href="https://style.tidyverse.org/">Tidyverse Style Guide</a></li>
<li>Google’s <a href="https://google.github.io/styleguide/Rguide.xml">R Style Guide</a></li>
</ul>
</section>
</section>
<section id="tips-on-rendering-to-a-pdf" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Tips on rendering to a PDF</h1>
<p>While Markdown files most easily render to<code>.html</code>, You may want to knit your R Markdown directly to a <code>.pdf</code>. This is very easy; although sometimes you may need to install an extra package. To check whether your computer is already set up to knit to <code>.pdf</code>, try selecting the drop-down from the ‘Knit’ button and choosing ‘Knit to PDF’ (or change your header, as described below). If that doesn’t work, you’ll have to install the <code>tinytex</code> package. You can do this within R if you use the <a href="https://yihui.name/tinytex/">tinytex</a> package, which is a minimal TeX package for R users.</p>
<pre><code>install.packages('tinytex', repos = 'http://cran.r-project.org')
tinytex::install_tinytex()</code></pre>
<p>You would only need to run these commands once. You would not normally include them in a regular R script, as doing so would needlessly repeat the installation, unless you take special precautions, such as wrapping the code in an <code>if</code> block as as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----install tinytex-----</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="fu">Sys.which</span>(<span class="st">'texi2dvi'</span>))) {</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># This can take a long time to run</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(<span class="st">'tinytex'</span>, <span class="at">repos =</span> <span class="st">'http://cran.r-project.org'</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    tinytex<span class="sc">::</span><span class="fu">install_tinytex</span>(<span class="at">force=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (tinytex<span class="sc">:::</span><span class="fu">is_tinytex</span>() <span class="sc">!=</span> <span class="cn">TRUE</span>) <span class="fu">warning</span>(<span class="st">'tinytex failed to install!'</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you need a more complete TeX package for other uses, you will need to download and install more software, separately from R. For Windows users, there is an awesome tutorial <a href="https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-windows-10-952b0c48bfa9">here</a>, and there is also a <a href="https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-macos-high-sierra-e7b5705c9fd">Mac version</a>.<br>
This will walk you through what you need to install (it also goes through installing R and RStudio, but you can just skip that). Once everything is installed, you can set your output to <code>pdf_document</code> instead of <code>html_document</code> to switch between <code>.html</code> and <code>.pdf</code> files.</p>
</section>
<section id="appendix" class="level1 unnumbered">
<h1 class="unnumbered">Appendix</h1>
<section id="session-information-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="session-information-1">Session information</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----session info------</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.6.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.5.1 dplyr_1.1.4   readr_2.1.5   knitr_1.48    pacman_0.5.1 

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       cli_3.6.3         rlang_1.1.4       xfun_0.47        
 [5] generics_0.1.3    jsonlite_1.8.8    glue_1.7.0        colorspace_2.1-1 
 [9] htmltools_0.5.8.1 hms_1.1.3         scales_1.3.0      fansi_1.0.6      
[13] rmarkdown_2.28    grid_4.3.1        munsell_0.5.1     evaluate_0.24.0  
[17] tibble_3.2.1      tzdb_0.4.0        fastmap_1.2.0     yaml_2.3.10      
[21] lifecycle_1.0.4   compiler_4.3.1    htmlwidgets_1.6.4 pkgconfig_2.0.3  
[25] rstudioapi_0.16.0 digest_0.6.37     R6_2.5.1          tidyselect_1.2.1 
[29] utf8_1.2.4        pillar_1.9.0      magrittr_2.0.3    withr_3.0.1      
[33] gtable_0.3.5      tools_4.3.1      </code></pre>
</div>
</div>
</section>
<section id="embedded-code" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="embedded-code">Embedded code</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----setup------</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set knitr options:</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>, <span class="at">messages =</span> <span class="cn">FALSE</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tidy.opts=</span><span class="fu">list</span>(<span class="at">width.cutoff =</span> <span class="dv">80</span>, <span class="at">blank =</span> <span class="cn">TRUE</span>) )</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set R option: show only 2 digits when displaying</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">4</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Clear workspace of all objects and unload all extra (non-base) packages</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>(<span class="at">all =</span> <span class="cn">TRUE</span>))</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(<span class="fu">sessionInfo</span>()<span class="sc">$</span>otherPkgs)) {</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">lapply</span>(<span class="fu">paste</span>(<span class="st">'package:'</span>, <span class="fu">names</span>(<span class="fu">sessionInfo</span>()<span class="sc">$</span>otherPkgs), <span class="at">sep=</span><span class="st">""</span>),</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>               detach, <span class="at">character.only=</span><span class="cn">TRUE</span>, <span class="at">unload=</span><span class="cn">TRUE</span>, <span class="at">force=</span><span class="cn">TRUE</span>))</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Load key packages using pacman (see below for explanation)</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>my_repo <span class="ot">&lt;-</span> <span class="st">'http://cran.r-project.org'</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>, <span class="at">repos =</span> my_repo)}</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the other packages, installing as needed</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Key principle:  Only load the packages you will need</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(knitr, readr, dplyr, ggplot2)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk-----------</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Code goes here; output appears below</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a><span class="co"># By setting the seed, we follow the reproducible research practice that my</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a><span class="co"># random numbers are the same each time.</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">45</span>)</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate random numbers from a Normal distribution and save as a vector.</span></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">2</span>, <span class="at">n=</span><span class="dv">20</span>)</span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a><span class="co">#-----code chunk that will not run----</span></span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a><span class="co"># This code won't be run!</span></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(I can type whatever I want because this is not run.)</span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk that will not be shown-----</span></span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a><span class="co"># This code won't be shown, but it will be run and output will show up.</span></span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb26-48"><a href="#cb26-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-49"><a href="#cb26-49" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk that will not show output------</span></span>
<span id="cb26-50"><a href="#cb26-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-51"><a href="#cb26-51" aria-hidden="true" tabindex="-1"></a><span class="co"># This output won't be shown, but it will still run in R.</span></span>
<span id="cb26-52"><a href="#cb26-52" aria-hidden="true" tabindex="-1"></a>mean_of_a <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)</span>
<span id="cb26-53"><a href="#cb26-53" aria-hidden="true" tabindex="-1"></a>mean_of_a</span>
<span id="cb26-54"><a href="#cb26-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-55"><a href="#cb26-55" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk hides everything----------</span></span>
<span id="cb26-56"><a href="#cb26-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-57"><a href="#cb26-57" aria-hidden="true" tabindex="-1"></a><span class="co"># This would be how to do all your coding for which you don't want to show the</span></span>
<span id="cb26-58"><a href="#cb26-58" aria-hidden="true" tabindex="-1"></a><span class="co"># output in your lab report. All this code runs, but nothing shows up in your</span></span>
<span id="cb26-59"><a href="#cb26-59" aria-hidden="true" tabindex="-1"></a><span class="co"># knitted document. Any variable I create here will be 'remembered' for the rest</span></span>
<span id="cb26-60"><a href="#cb26-60" aria-hidden="true" tabindex="-1"></a><span class="co"># of this knitted document.</span></span>
<span id="cb26-61"><a href="#cb26-61" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb26-62"><a href="#cb26-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-63"><a href="#cb26-63" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example chunk accept errors-----</span></span>
<span id="cb26-64"><a href="#cb26-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-65"><a href="#cb26-65" aria-hidden="true" tabindex="-1"></a><span class="co"># Sometimes in a work-in-progress, you may want a knitted copy of everything -</span></span>
<span id="cb26-66"><a href="#cb26-66" aria-hidden="true" tabindex="-1"></a><span class="co"># even things that go wrong. This wouldn't be a chunk option to use in a</span></span>
<span id="cb26-67"><a href="#cb26-67" aria-hidden="true" tabindex="-1"></a><span class="co"># polished homework assignment. This is an error because I haven't loaded the</span></span>
<span id="cb26-68"><a href="#cb26-68" aria-hidden="true" tabindex="-1"></a><span class="co"># titanic data in this document yet (regardless of whether it's loaded in my</span></span>
<span id="cb26-69"><a href="#cb26-69" aria-hidden="true" tabindex="-1"></a><span class="co"># RStudio right now)</span></span>
<span id="cb26-70"><a href="#cb26-70" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(titanic) </span>
<span id="cb26-71"><a href="#cb26-71" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span>
<span id="cb26-72"><a href="#cb26-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-73"><a href="#cb26-73" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example plot-----</span></span>
<span id="cb26-74"><a href="#cb26-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-75"><a href="#cb26-75" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(a)</span>
<span id="cb26-76"><a href="#cb26-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-77"><a href="#cb26-77" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example plot is hidden----------</span></span>
<span id="cb26-78"><a href="#cb26-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-79"><a href="#cb26-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Still run in R, though!</span></span>
<span id="cb26-80"><a href="#cb26-80" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(a)</span>
<span id="cb26-81"><a href="#cb26-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-82"><a href="#cb26-82" aria-hidden="true" tabindex="-1"></a><span class="co">#-----example table with data generation----</span></span>
<span id="cb26-83"><a href="#cb26-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-84"><a href="#cb26-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate some toy data as vectors</span></span>
<span id="cb26-85"><a href="#cb26-85" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">n =</span> <span class="dv">20</span>, <span class="at">prob =</span> .<span class="dv">5</span>)</span>
<span id="cb26-86"><a href="#cb26-86" aria-hidden="true" tabindex="-1"></a>height <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">mean =</span> (<span class="dv">50</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> sex), <span class="at">sd =</span> <span class="dv">10</span>, <span class="at">n =</span> <span class="dv">20</span>)</span>
<span id="cb26-87"><a href="#cb26-87" aria-hidden="true" tabindex="-1"></a>hair_color <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"brown"</span>, <span class="st">"black"</span>, <span class="st">"blond"</span>), <span class="at">length =</span> <span class="dv">20</span>)</span>
<span id="cb26-88"><a href="#cb26-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-89"><a href="#cb26-89" aria-hidden="true" tabindex="-1"></a><span class="co"># combine within a "tibble" dataframe, oriented by columns</span></span>
<span id="cb26-90"><a href="#cb26-90" aria-hidden="true" tabindex="-1"></a>toy.data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(sex, height, hair_color)</span>
<span id="cb26-91"><a href="#cb26-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-92"><a href="#cb26-92" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table with the average and standard deviation of height for each </span></span>
<span id="cb26-93"><a href="#cb26-93" aria-hidden="true" tabindex="-1"></a><span class="co"># hair color category using `dplyr` functions and the pipe operator, `%&gt;%`, which </span></span>
<span id="cb26-94"><a href="#cb26-94" aria-hidden="true" tabindex="-1"></a><span class="co"># feeds the output of one function into the input of the next function. </span></span>
<span id="cb26-95"><a href="#cb26-95" aria-hidden="true" tabindex="-1"></a><span class="co"># The `` notation acommodates non-standard variable names.</span></span>
<span id="cb26-96"><a href="#cb26-96" aria-hidden="true" tabindex="-1"></a>table_df <span class="ot">&lt;-</span> toy.data <span class="sc">%&gt;%</span> </span>
<span id="cb26-97"><a href="#cb26-97" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hair_color) <span class="sc">%&gt;%</span> </span>
<span id="cb26-98"><a href="#cb26-98" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Average height</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(height), </span>
<span id="cb26-99"><a href="#cb26-99" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">SD of height</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sd</span>(height), </span>
<span id="cb26-100"><a href="#cb26-100" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb26-101"><a href="#cb26-101" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">Hair color</span><span class="st">`</span> <span class="ot">=</span> hair_color)</span>
<span id="cb26-102"><a href="#cb26-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-103"><a href="#cb26-103" aria-hidden="true" tabindex="-1"></a><span class="co">#example kable table with caption</span></span>
<span id="cb26-104"><a href="#cb26-104" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(table_df, <span class="at">caption=</span><span class="st">"Height by hair color"</span>)</span>
<span id="cb26-105"><a href="#cb26-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-106"><a href="#cb26-106" aria-hidden="true" tabindex="-1"></a><span class="co">#-----file paths---------</span></span>
<span id="cb26-107"><a href="#cb26-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-108"><a href="#cb26-108" aria-hidden="true" tabindex="-1"></a><span class="co"># Only works on Windows, as other modern operating systems (macOS, Linux) do </span></span>
<span id="cb26-109"><a href="#cb26-109" aria-hidden="true" tabindex="-1"></a><span class="co"># not support "drive letters", such as "P:"</span></span>
<span id="cb26-110"><a href="#cb26-110" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'P:</span><span class="sc">\\</span><span class="st">ENVH556'</span></span>
<span id="cb26-111"><a href="#cb26-111" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'P:/ENVH556'</span></span>
<span id="cb26-112"><a href="#cb26-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-113"><a href="#cb26-113" aria-hidden="true" tabindex="-1"></a><span class="co"># Will not work on Windows, exposes your username, and won't work for other </span></span>
<span id="cb26-114"><a href="#cb26-114" aria-hidden="true" tabindex="-1"></a><span class="co"># users</span></span>
<span id="cb26-115"><a href="#cb26-115" aria-hidden="true" tabindex="-1"></a>full_path <span class="ot">&lt;-</span> <span class="st">'/Users/joanna/ENVH556'</span></span>
<span id="cb26-116"><a href="#cb26-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-117"><a href="#cb26-117" aria-hidden="true" tabindex="-1"></a><span class="co"># If you are curious about what the "~" expands to, you can use path.expand()</span></span>
<span id="cb26-118"><a href="#cb26-118" aria-hidden="true" tabindex="-1"></a>full_path_to_home <span class="ot">&lt;-</span> <span class="fu">path.expand</span>(<span class="st">'~'</span>)</span>
<span id="cb26-119"><a href="#cb26-119" aria-hidden="true" tabindex="-1"></a>full_path_to_data <span class="ot">&lt;-</span> <span class="fu">path.expand</span>(<span class="st">'~/ENVH556'</span>)</span>
<span id="cb26-120"><a href="#cb26-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-121"><a href="#cb26-121" aria-hidden="true" tabindex="-1"></a><span class="co"># Will work on Windows, macOS, and Linux, etc., if the file is in the user's</span></span>
<span id="cb26-122"><a href="#cb26-122" aria-hidden="true" tabindex="-1"></a><span class="co"># "home directory"</span></span>
<span id="cb26-123"><a href="#cb26-123" aria-hidden="true" tabindex="-1"></a>relative_path <span class="ot">&lt;-</span> <span class="st">'~/ENVH556'</span></span>
<span id="cb26-124"><a href="#cb26-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-125"><a href="#cb26-125" aria-hidden="true" tabindex="-1"></a><span class="co">#-----relative path example-----</span></span>
<span id="cb26-126"><a href="#cb26-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-127"><a href="#cb26-127" aria-hidden="true" tabindex="-1"></a><span class="co"># assign working directory variable</span></span>
<span id="cb26-128"><a href="#cb26-128" aria-hidden="true" tabindex="-1"></a>work_dir <span class="ot">&lt;-</span> <span class="fu">getwd</span>()</span>
<span id="cb26-129"><a href="#cb26-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-130"><a href="#cb26-130" aria-hidden="true" tabindex="-1"></a><span class="co"># build relative path to data file</span></span>
<span id="cb26-131"><a href="#cb26-131" aria-hidden="true" tabindex="-1"></a>relative_data_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(work_dir, <span class="st">"Datasets"</span>, <span class="st">"data.rds"</span>)</span>
<span id="cb26-132"><a href="#cb26-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-133"><a href="#cb26-133" aria-hidden="true" tabindex="-1"></a><span class="co"># load data, assign to "df" variable</span></span>
<span id="cb26-134"><a href="#cb26-134" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(relative_data_path)</span>
<span id="cb26-135"><a href="#cb26-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-136"><a href="#cb26-136" aria-hidden="true" tabindex="-1"></a><span class="co">#-----setwd example---------</span></span>
<span id="cb26-137"><a href="#cb26-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-138"><a href="#cb26-138" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a full file path, but it would be better to use a relative one</span></span>
<span id="cb26-139"><a href="#cb26-139" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"P:/ENVH556"</span>)</span>
<span id="cb26-140"><a href="#cb26-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-141"><a href="#cb26-141" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a relative file path, where ".." means "one folder up"</span></span>
<span id="cb26-142"><a href="#cb26-142" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"../ENVH556"</span>)</span>
<span id="cb26-143"><a href="#cb26-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-144"><a href="#cb26-144" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we use a relative file path with file.path(), the recommended method</span></span>
<span id="cb26-145"><a href="#cb26-145" aria-hidden="true" tabindex="-1"></a><span class="co"># because this method supports muliple computing platforms (Windows, Mac, etc.)</span></span>
<span id="cb26-146"><a href="#cb26-146" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">file.path</span>(<span class="st">".."</span>, <span class="st">"ENVH556"</span>))</span>
<span id="cb26-147"><a href="#cb26-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-148"><a href="#cb26-148" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we are ready to read the file</span></span>
<span id="cb26-149"><a href="#cb26-149" aria-hidden="true" tabindex="-1"></a>DEMS <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"DEMSCombinedPersonal.rds"</span>)</span>
<span id="cb26-150"><a href="#cb26-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-151"><a href="#cb26-151" aria-hidden="true" tabindex="-1"></a><span class="co"># You can see that my working directory changed with getwd()</span></span>
<span id="cb26-152"><a href="#cb26-152" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span>
<span id="cb26-153"><a href="#cb26-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-154"><a href="#cb26-154" aria-hidden="true" tabindex="-1"></a><span class="co">#-----setup pacman-----------</span></span>
<span id="cb26-155"><a href="#cb26-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-156"><a href="#cb26-156" aria-hidden="true" tabindex="-1"></a><span class="co"># Not evaluated here since done at the beginning of the file</span></span>
<span id="cb26-157"><a href="#cb26-157" aria-hidden="true" tabindex="-1"></a><span class="co"># Load pacman into memory, installing as needed</span></span>
<span id="cb26-158"><a href="#cb26-158" aria-hidden="true" tabindex="-1"></a>my_repo <span class="ot">&lt;-</span> <span class="st">'http://cran.r-project.org'</span></span>
<span id="cb26-159"><a href="#cb26-159" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) {<span class="fu">install.packages</span>(<span class="st">"pacman"</span>, <span class="at">repos =</span> my_repo)}</span>
<span id="cb26-160"><a href="#cb26-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-161"><a href="#cb26-161" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the other packages, installing as needed</span></span>
<span id="cb26-162"><a href="#cb26-162" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(knitr, tidyverse)</span>
<span id="cb26-163"><a href="#cb26-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-164"><a href="#cb26-164" aria-hidden="true" tabindex="-1"></a><span class="co">#-----comment example-----------</span></span>
<span id="cb26-165"><a href="#cb26-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-166"><a href="#cb26-166" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector of temperatures in degrees Celcius</span></span>
<span id="cb26-167"><a href="#cb26-167" aria-hidden="true" tabindex="-1"></a>temps <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">22</span>, <span class="dv">20</span>, <span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">22</span>, <span class="dv">19</span>)</span>
<span id="cb26-168"><a href="#cb26-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-169"><a href="#cb26-169" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean temperature and standard deviation</span></span>
<span id="cb26-170"><a href="#cb26-170" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(temps)</span>
<span id="cb26-171"><a href="#cb26-171" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(temps)</span>
<span id="cb26-172"><a href="#cb26-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-173"><a href="#cb26-173" aria-hidden="true" tabindex="-1"></a><span class="co">#-----install tinytex-----</span></span>
<span id="cb26-174"><a href="#cb26-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-175"><a href="#cb26-175" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="fu">Sys.which</span>(<span class="st">'texi2dvi'</span>))) {</span>
<span id="cb26-176"><a href="#cb26-176" aria-hidden="true" tabindex="-1"></a>    <span class="co"># This can take a long time to run</span></span>
<span id="cb26-177"><a href="#cb26-177" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(<span class="st">'tinytex'</span>, <span class="at">repos =</span> <span class="st">'http://cran.r-project.org'</span>)</span>
<span id="cb26-178"><a href="#cb26-178" aria-hidden="true" tabindex="-1"></a>    tinytex<span class="sc">::</span><span class="fu">install_tinytex</span>(<span class="at">force=</span><span class="cn">TRUE</span>)</span>
<span id="cb26-179"><a href="#cb26-179" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (tinytex<span class="sc">:::</span><span class="fu">is_tinytex</span>() <span class="sc">!=</span> <span class="cn">TRUE</span>) <span class="fu">warning</span>(<span class="st">'tinytex failed to install!'</span>)</span>
<span id="cb26-180"><a href="#cb26-180" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-181"><a href="#cb26-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-182"><a href="#cb26-182" aria-hidden="true" tabindex="-1"></a><span class="co">#-----session info------</span></span>
<span id="cb26-183"><a href="#cb26-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-184"><a href="#cb26-184" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb26-185"><a href="#cb26-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-186"><a href="#cb26-186" aria-hidden="true" tabindex="-1"></a><span class="co">#-----code appendix-------</span></span>
<span id="cb26-187"><a href="#cb26-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-188"><a href="#cb26-188" aria-hidden="true" tabindex="-1"></a><span class="co">#-----functions defined in this Rmd ------------</span></span>
<span id="cb26-189"><a href="#cb26-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-190"><a href="#cb26-190" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the names of all functions defined in the .qmd</span></span>
<span id="cb26-191"><a href="#cb26-191" aria-hidden="true" tabindex="-1"></a><span class="co"># (e.g. loaded in the environment)</span></span>
<span id="cb26-192"><a href="#cb26-192" aria-hidden="true" tabindex="-1"></a><span class="fu">lsf.str</span>()</span>
<span id="cb26-193"><a href="#cb26-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-194"><a href="#cb26-194" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the definitions of all functions loaded into the current environment  </span></span>
<span id="cb26-195"><a href="#cb26-195" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(<span class="fu">c</span>(<span class="fu">lsf.str</span>()), getAnywhere)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="custom-functions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="custom-functions">Custom functions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----functions defined in this Rmd ------------</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the names of all functions defined in the .qmd</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (e.g. loaded in the environment)</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lsf.str</span>()</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the definitions of all functions loaded into the current environment  </span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(<span class="fu">c</span>(<span class="fu">lsf.str</span>()), getAnywhere)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>list()</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>